local wk = require("which-key")
wk.add({
  { "<leader>kr", group = "rust_cmds" }, -- group for rust commands
  { "<leader>krd", ":RustLsp debuggables<CR>", desc = "List debug targets" },
  { "<leader>krD", ":RustLsp debug<CR>", desc = "Start debug session" },
  { "<leader>krr", ":RustLsp runnables<CR>", desc = "List run targets" },
  { "<leader>krR", ":RustLsp run<CR>", desc = "Run target" },
  { "<leader>krt", ":RustLsp testables<CR>", desc = "List test targets" },
  { "<leader>krT", ":RustLsp test<CR>", desc = "Run tests" },
  { "<leader>krk", ":RustLsp expandMacro<CR>", desc = "Expand macros recursively" },
  { "<leader>krp", ":RustLsp rebuildProcMacros<CR>", desc = "Rebuild procedural macros" },
  { "<leader>kru", ":RustLsp moveItem up<CR>", desc = "Move item up" },
  { "<leader>krn", ":RustLsp moveItem down<CR>", desc = "Move item down" },
  { "<leader>krc", ":RustLsp codeAction<CR>", desc = "Code actions" },
  { "<leader>krh", ":RustLsp hover actions<CR>", desc = "Hover actions" },
  { "<leader>kre", ":RustLsp explainError<CR>", desc = "Explain error" },
  { "<leader>krC", ":RustLsp openCargo<CR>", desc = "Open Cargo.toml" },
  { "<leader>kro", ":RustLsp openDocs<CR>", desc = "Open online docs" },
  { "<leader>krP", ":RustLsp parentModule<CR>", desc = "Parent module" },
  { "<leader>krj", ":RustLsp joinLines<CR>", desc = "Join lines" },
  { "<leader>krs", ":RustLsp ssr<CR>", desc = "Structural search replace" },
  { "<leader>krg", ":RustLsp crateGraph<CR>", desc = "Crate graph" },
  { "<leader>krS", ":RustLsp syntaxTree<CR>", desc = "Syntax tree" },
  { "<leader>krm", ":RustFmt<CR>", desc = "Format file" },
  { "<leader>krf", ":RustFmt<CR>", desc = "Format file" },
  { "<leader>krx", ":RustLsp flyCheck<CR>", desc = "Fly check" },
  { "<leader>krv", ":RustLsp view hir<CR>", desc = "View HIR" },
  { "<leader>krV", ":RustLsp view mir<CR>", desc = "View MIR" },
})




-- local rust_cmds = {
--     name = "Rust Commands",
--     d = {":RustLsp debuggables<CR>", 'List debug targets'},
--     D = {":RustLsp debug<CR>", 'Start debug session'},
--     r = {":RustLsp runnables<CR>", 'List run targets'},
--     R = {":RustLsp run<CR>", 'Run target'},
--     t = {":RustLsp testables<CR>", 'List test targets'},
--     T = {":RustLsp test<CR>", 'Run tests'},
--     k = {":RustLsp expandMacro<CR>", 'Expand macros recursively'},
--     p = {":RustLsp rebuildProcMacros<CR>", 'Rebuild procedural macros'},
--     u = {":RustLsp moveItem up<CR>", 'Move item up'},
--     n = {":RustLsp moveItem down<CR>", 'Move item down'},
--     c = {":RustLsp codeAction<CR>", 'Code actions'},
--     h = {":RustLsp hover actions<CR>", 'Hover actions'},
--     e = {":RustLsp explainError<CR>", 'Explain error'},
--     C = {":RustLsp openCargo<CR>", 'Open Cargo.toml'},
--     o = {":RustLsp openDocs<CR>", 'Open online docs'},
--     P = {":RustLsp parentModule<CR>", 'Parent module'},
--     j = {":RustLsp joinLines<CR>", 'Join lines'},
--     s = {":RustLsp ssr<CR>", 'Structural search replace'},
--     g = {":RustLsp crateGraph<CR>", 'Crate graph'},
--     S = {":RustLsp syntaxTree<CR>", 'Syntax tree'},
--     m = {":RustFmt<CR>", 'Format file'},
--     f = {":RustFmt<CR>", 'Format file'},
--     x = {":RustLsp flyCheck<CR>", 'Fly check'},
--     -- fc = {":RustLsp flyCheck<CR>", 'Fly check'},
--     -- ff = {":RustFmt<CR>", 'Format file'},
--     -- fr = {":RustFmt Range<CR>", 'Format Range'},
--     v = {":RustLsp view hir<CR>", 'View HIR'},
--     V = {":RustLsp view mir<CR>", 'View MIR'},
-- }
--
-- return rust_cmds
