local wk = require("which-key")

wk.add({
  { "<leader>c", group = "comment_box_cmds" }, -- group for comment box commands
  { "<leader>C", group = "copilot_cmds" }, -- group for copilot commands
  { "<leader>l", group = "leetcode_cmds" }, -- group for leetcode commands
  { "<leader>r", group = "rust_cmds" }, -- group for rust commands
  { "<leader>t", group = "telescope_cmds" }, -- group for telescope commands
  { "<leader>v", group = "visual_multi_cmds" }, -- group for visual multi commands
})

wk.add({
  { "<leader>cb", desc = "Boxes" },
  { "<leader>cb", desc = "Boxes Description" },
  { "<leader>cbl", "<Cmd>CBllbox<CR>", desc = "Left Aligned Box" },
  { "<leader>cblc", "<Cmd>CBlcbox<CR>", desc = "Left Aligned Centered Text Box" },
  { "<leader>cblr", "<Cmd>CBlrbox<CR>", desc = "Left Aligned Right Text Box" },
  { "<leader>cbcl", "<Cmd>CBclbox<CR>", desc = "Centered Left Text Box" },
  { "<leader>cbcc", "<Cmd>CBccbox<CR>", desc = "Centered Box Title" },
  { "<leader>cbcr", "<Cmd>CBcrbox<CR>", desc = "Centered Right Text Box" },
  { "<leader>cbrl", "<Cmd>CBrlbox<CR>", desc = "Right Aligned Left Text Box" },
  { "<leader>cbrc", "<Cmd>CBrcbox<CR>", desc = "Right Aligned Centered Text Box" },
  { "<leader>cbrr", "<Cmd>CBrrbox<CR>", desc = "Right Aligned Right Text Box" },
  { "<leader>cba", "<Cmd>CBlabox<CR>", desc = "Left Aligned Adapted Box" },
  { "<leader>cbc", "<Cmd>CBacbox<CR>", desc = "Centered Adapted Box" },
  { "<leader>cbr", "<Cmd>CBrabox<CR>", desc = "Right Aligned Adapted Box" },
  
  { "<leader>ct", desc = "Titled Lines" },
  { "<leader>ctl", "<Cmd>CBllline<CR>", desc = "Left Aligned Titled Line" },
  { "<leader>ctlc", "<Cmd>CBlcline<CR>", desc = "Left Aligned Centered Text Line" },
  { "<leader>ctlr", "<Cmd>CBlrline<CR>", desc = "Left Aligned Right Text Line" },
  { "<leader>ctcl", "<Cmd>CBclline<CR>", desc = "Centered Left Text Titled Line" },
  { "<leader>ctcc", "<Cmd>CBccline<CR>", desc = "Centered Centered Text Titled Line" },
  { "<leader>ctcr", "<Cmd>CBcrline<CR>", desc = "Centered Right Text Titled Line" },
  { "<leader>ctrl", "<Cmd>CBrlline<CR>", desc = "Right Aligned Left Text Titled Line" },
  { "<leader>ctrc", "<Cmd>CBrcline<CR>", desc = "Right Aligned Centered Text Titled Line" },
  { "<leader>ctrr", "<Cmd>CBrrline<CR>", desc = "Right Aligned Right Text Titled Line" },
  
  { "<leader>cs", desc = "Simple Lines" },
  { "<leader>csl", "<Cmd>CBline<CR>", desc = "Simple Left Aligned Line" },
  { "<leader>csc", "<Cmd>CBcline<CR>", desc = "Centered Line" },
  { "<leader>csr", "<Cmd>CBrline<CR>", desc = "Right Aligned Line" },
  
  { "<leader>co", desc = "Other Commands" },
  { "<leader>cod", "<Cmd>CBd<CR>", desc = "Remove Box or Line" },
  { "<leader>coy", "<Cmd>CBy<CR>", desc = "Yank Box Content" },
  { "<leader>coc", "<Cmd>CBcatalog<CR>", desc = "Open Catalog" },
  
  { "<leader>co", desc = "Copilot Commands" },
  { "<leader>coo", ":CopilotChatOpen<CR>", desc = "Open chat window" },
  { "<leader>coc", ":CopilotChatClose<CR>", desc = "Close chat window" },
  { "<leader>cot", ":CopilotChatToggle<CR>", desc = "Toggle chat window" },
  { "<leader>cos", ":CopilotChatStop<CR>", desc = "Stop current copilot output" },
  { "<leader>cor", ":CopilotChatReset<CR>", desc = "Reset chat window" },
  { "<leader>cov", ":CopilotChatSave<CR>", desc = "Save chat history to file" },
  { "<leader>col", ":CopilotChatLoad<CR>", desc = "Load chat history from file" },
  { "<leader>cod", ":CopilotChatDebugInfo<CR>", desc = "Show debug information" },
  { "<leader>coe", ":CopilotChatExplain<CR>", desc = "Write an explanation for the active selection as paragraphs of text" },
  { "<leader>cow", ":CopilotChatReview<CR>", desc = "Review the selected code" },
  { "<leader>cof", ":CopilotChatFix<CR>", desc = "Rewrite the code to show it with the bug fixed" },
  { "<leader>cop", ":CopilotChatOptimize<CR>", desc = "Optimize the selected code to improve performance and readability" },
  { "<leader>con", ":CopilotChatDocs<CR>", desc = "Add documentation comment for the selection" },
  { "<leader>cog", ":CopilotChatTests<CR>", desc = "Generate tests for my code" },
  { "<leader>cox", ":CopilotChatFixDiagnostic<CR>", desc = "Assist with the following diagnostic issue in file" },
  { "<leader>com", ":CopilotChatCommit<CR>", desc = "Write commit message for the change with commitizen convention" },
  { "<leader>coM", ":CopilotChatCommitStaged<CR>", desc = "Write commit message for the change with commitizen convention" },
  
  { "<leader>l", desc = "LeetCode Commands" },
  { "<leader>la", ":Leet random<CR>", desc = "Open a random question" },
  { "<leader>ls", ":Leet submit<CR>", desc = "Submit the current question" },
  { "<leader>ld", ":Leet daily<CR>", desc = "Open today's question" },
  { "<leader>lf", ":Leet list<CR>", desc = "Open problem list picker" },
  { "<leader>lg", ":Leet lang<CR>", desc = "Change language for current question" },
  { "<leader>lr", ":Leet run<CR>", desc = "Run the current question" },
  { "<leader>lt", ":Leet tabs<CR>", desc = "List all open question tabs" },
  { "<leader>ly", ":Leet yank<CR>", desc = "Yank the current solution" },
  { "<leader>lu", ":Leet session update<CR>", desc = "Update current session" },
  { "<leader>li", ":Leet info<CR>", desc = "Show information about the current question" },
  { "<leader>lo", ":Leet open<CR>", desc = "Open current question in browser" },
  { "<leader>lp", ":Leet inject<CR>", desc = "Re-inject code for current question" },
  { "<leader>lq", ":Leet desc<CR>", desc = "Toggle question description" },
  { "<leader>lj", ":Leet session create<CR>", desc = "Create a new session" },
  { "<leader>lk", ":Leet cache update<CR>", desc = "Update cache" },
  { "<leader>ll", ":Leet last_submit<CR>", desc = "Retrieve last submitted code" },
  { "<leader>lz", ":Leet restore<CR>", desc = "Restore default question layout" },
  { "<leader>lx", ":Leet reset<CR>", desc = "Reset current question to default" },
  { "<leader>lc", ":Leet console<CR>", desc = "Open console for current question" },
  { "<leader>lv", ":Leet random status=<status> difficulty=<difficulty> tags=<tags><CR>", desc = "Filter random problem" },
  { "<leader>lb", ":Leet list status=<status> difficulty=<difficulty><CR>", desc = "Filter problem list" },
  { "<leader>ln", ":Leet session change<CR>", desc = "Change current session" },
  { "<leader>lm", ":Leet<CR>", desc = "Open LeetCode Menu" },
  { "<leader>lw", ":Leet cookie update<CR>", desc = "Update cookie" },
  { "<leader>le", ":Leet cookie delete<CR>", desc = "Delete cookie" },
  
  { "<leader>r", desc = "Rust Commands" },
  { "<leader>rd", ":RustLsp debuggables<CR>", desc = "List debug targets" },
  { "<leader>rD", ":RustLsp debug<CR>", desc = "Start debug session" },
  { "<leader>rr", ":RustLsp runnables<CR>", desc = "List run targets" },
  { "<leader>rR", ":RustLsp run<CR>", desc = "Run target" },
  { "<leader>rt", ":RustLsp testables<CR>", desc = "List test targets" },
  { "<leader>rT", ":RustLsp test<CR>", desc = "Run tests" },
  { "<leader>rk", ":RustLsp expandMacro<CR>", desc = "Expand macros recursively" },
  { "<leader>rp", ":RustLsp rebuildProcMacros<CR>", desc = "Rebuild procedural macros" },
  { "<leader>ru", ":RustLsp moveItem up<CR>", desc = "Move item up" },
  { "<leader>rn", ":RustLsp moveItem down<CR>", desc = "Move item down" },
  { "<leader>rc", ":RustLsp codeAction<CR>", desc = "Code actions" },
  { "<leader>rh", ":RustLsp hover actions<CR>", desc = "Hover actions" },
  { "<leader>re", ":RustLsp explainError<CR>", desc = "Explain error" },
  { "<leader>rC", ":RustLsp openCargo<CR>", desc = "Open Cargo.toml" },
  { "<leader>ro", ":RustLsp openDocs<CR>", desc = "Open online docs" },
  { "<leader>rP", ":RustLsp parentModule<CR>", desc = "Parent module" },
  { "<leader>rj", ":RustLsp joinLines<CR>", desc = "Join lines" },
  { "<leader>rs", ":RustLsp ssr<CR>", desc = "Structural search replace" },
  { "<leader>rg", ":RustLsp crateGraph<CR>", desc = "Crate graph" },
  { "<leader>rS", ":RustLsp syntaxTree<CR>", desc = "Syntax tree" },
  { "<leader>rm", ":RustFmt<CR>", desc = "Format file" },
  { "<leader>rf", ":RustFmt<CR>", desc = "Format file" },
  { "<leader>rx", ":RustLsp flyCheck<CR>", desc = "Fly check" },
  { "<leader>rv", ":RustLsp view hir<CR>", desc = "View HIR" },
  { "<leader>rV", ":RustLsp view mir<CR>", desc = "View MIR" },
  
  { "<leader>t", desc = "Telescope Commands" },
  { "<leader>tf", "<cmd>Telescope find_files<cr>", desc = "Find Files" },
  { "<leader>tg", "<cmd>Telescope live_grep<cr>", desc = "Live Grep" },
  { "<leader>tb", "<cmd>Telescope buffers<cr>", desc = "Find Buffers" },
  { "<leader>th", "<cmd>Telescope help_tags<cr>", desc = "Help Tags" },
  { "<leader>tr", "<cmd>Telescope lsp_references<cr>", desc = "Search References" },
  { "<leader>tI", "<cmd>Telescope lsp_incoming_calls<cr>", desc = "Incoming Calls" },
  { "<leader>tO", "<cmd>Telescope lsp_outgoing_calls<cr>", desc = "Outgoing Calls" },
  { "<leader>td", "<cmd>Telescope lsp_definitions<cr>", desc = "Go to Definitions" },
  { "<leader>tt", "<cmd>Telescope lsp_type_definitions<cr>", desc = "Definition of current type" },
  { "<leader>ti", "<cmd>Telescope lsp_implementations<cr>", desc = "Go to Implementations" },
  { "<leader>ts", "<cmd>Telescope lsp_document_symbols<cr>", desc = "Document Symbols" },
  { "<leader>tw", "<cmd>Telescope lsp_workspace_symbols<cr>", desc = "Workspace Symbols" },
  { "<leader>tx", "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>", desc = "Dynamic Workspace Symbols" },
  { "<leader>tD", "<cmd>Telescope diagnostics<cr>", desc = "Document Diagnostics" },
  
  { "<leader>v", desc = "Visual Multi" },
  { "<leader>vm", "<Plug>(VM-Find-Under)", desc = "Find Under Cursor" },
  { "<leader>vM", "<Plug>(VM-Find-Subword-Under)", desc = "Find Subword Under Cursor" },
  { "<leader>va", "<Plug>(VM-Select-All)", desc = "Select All Occurrences" },
  { "<leader>vh", "<Plug>(VM-Select-h)", desc = "Select h" },
  { "<leader>vl", "<Plug>(VM-Select-l)", desc = "Select l" },
  { "<leader>vj", "<Plug>(VM-Select-j)", desc = "Select j" },
  { "<leader>vk", "<Plug>(VM-Select-k)", desc = "Select k" },
  { "<leader>vn", "<Plug>(VM-Next)", desc = "Select Next" },
  { "<leader>vN", "<Plug>(VM-Prev)", desc = "Select Previous" },
  { "<leader>vq", "<Plug>(VM-Skip)", desc = "Skip Current" },
  { "<leader>vQ", "<Plug>(VM-Remove)", desc = "Remove Current" },
  { "<leader>vi", "<Plug>(VM-Insert)", desc = "Start Insert Mode" },
  { "<leader>vA", "<Plug>(VM-Append)", desc = "Start Append Mode" },
  { "<leader><D-d>", "<Plug>(VM-Add-Cursor-Down)", desc = "Add Cursor Down" },
  { "<leader><D-u>", "<Plug>(VM-Add-Cursor-Up)", desc = "Add Cursor Up" },
  { "<leader><C-Down>", "<Plug>(VM-Add-Cursor-Down)", desc = "Add Cursor Down" },
  { "<leader><C-Up>", "<Plug>(VM-Add-Cursor-Up)", desc = "Add Cursor Up" },
})
