-- Smooth cursor movement.
-- Sounds like a good idea, but it's not working for me.
-- Slows down cursor movement and makes it jerky.
-- return {
--   "sphamba/smear-cursor.nvim",
--   opts = {},
-- }
